### ISSUE TITLE
ImportError: cannot import name 'SortedDict'

### ISSUE THREAD

**Issue by kundansable** [willhardy/django-seo#59]
I was trying to integrate this package with my project, I have django v1.10.3 used in my project
I am getting this error "ImportError: cannot import name 'SortedDict'" in file "rollyourown/seo/base.py"
may be you haven't updated your repo for latest version of django ,  SortedDict deprecated and Removed in Django 1.9

**Comment by jonperron** [comment]
It has not been updated since 3 years ago, so it's still stuck at Django 1.7.

**Comment by lawrencemq** [comment]
Any updates on this? It'd be great if we could get this to work with Django 1.11
If the project owner is still around, I could try to make a PR with an updated to an OrderedDict instead.

**Comment by bulatshafigullin** [comment]
This project is abandoned, I've switched to [django-seo2](https://github.com/romansalin/django-seo2).
